# Generated by Django 6.0.4 on 2026-04-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_managers_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='max_patients_per_slot',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد المرضى في نفس الوقت'),
        ),
    ]
