# Generated by Django 6.0.4 on 2026-04-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('checked_in', 'حضر إلى العيادة'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
