# Generated by Django 6.0.4 on 2026-05-02 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time'], 'verbose_name': 'موعد', 'verbose_name_plural': 'المواعيد'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appointment_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(blank=True, max_length=150, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(default='استشارة عامة', max_length=150, verbose_name='نوع الزيارة'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='المريض'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='سبب الزيارة'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
