# Generated by Django 6.0.4 on 2026-04-30 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_doctorprofile_max_patients_per_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='بداية العمل')),
                ('end_time', models.TimeField(verbose_name='نهاية العمل')),
                ('max_patients_per_slot', models.PositiveIntegerField(default=1, verbose_name='عدد المرضى في نفس الوقت')),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='authentication.doctorprofile', verbose_name='الطبيب')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
